### ISSUE TITLE
大佬好，我找不到power.log

### ISSUE THREAD

**Issue by ttc-oss** [Yiyuan-Dong/AutoHS#7]
我在cmd运行结果如下：
C:\Users\silent>C:\Users\silent\Downloads\AutoHS-main\main.py
[21:48:21 SYS] cards.json已存在
[21:48:21 WARN] Fail to truncate Power.log, maybe someone is using it
[21:48:21 SYS] Enter State Choosing Hero
[21:48:25 SYS] Enter State Match Opponent
Traceback (most recent call last):
  File "C:\Users\silent\Downloads\AutoHS-main\main.py", line 12, in <module>
    AutoHS_automata()
  File "C:\Users\silent\Downloads\AutoHS-main\FSM_action.py", line 378, in AutoHS_automata
    FSM_state = FSM_dispatch(FSM_state)
  File "C:\Users\silent\Downloads\AutoHS-main\FSM_action.py", line 367, in FSM_dispatch
    return dispatch_dict[next_state]()
  File "C:\Users\silent\Downloads\AutoHS-main\FSM_action.py", line 123, in MatchingAction
    ok = update_game_state()
  File "C:\Users\silent\Downloads\AutoHS-main\FSM_action.py", line 48, in update_game_state
    log_container = next(log_iter)
  File "C:\Users\silent\Downloads\AutoHS-main\log_op.py", line 186, in log_iter_func
    with open(path, "r", encoding="utf8") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Hearthstone\\Logs'

我的炉石log路径当中没有power.log，您知道是什么问题吗？

**Comment by Yiyuan-Dong** [comment]
Power.log只会在进入对战后生成，在退出炉石时可能会被删除，所以可能出现有其他`*.log`文件但没有`Power.log`的情况，你可以在对战中看看`Logs\`文件夹。
你的路径可以直接用`C:\Program Files\Hearthstone\Logs\Power.log`。 如果脚本发现找不到`Power.log`会等待它的生成。

**Comment by ttc-oss** [comment]
大佬，碍于GitHub上无法将这里的截图发出，我确信没有Power.log这个文件。
能否留一个邮箱方便联系呢？

**Comment by Yiyuan-Dong** [comment]
852427139@qq.com
